//
//  quotes.swift
//  task manager
//
//  Created by Navneet Dagdiya on 9/3/2026.
//

import Foundation

struct Quotes {
    static let quotes = [
        "Believe in yourself!",
        "Carpe diem — seize the day.",
        "The only limit is your mind.",
        "Keep moving forward.",
        "Dream big, work hard.",
        "Success is the sum of small efforts repeated daily.",
        "Don't watch the clock; do what it does — keep going.",
        "Failure is not the opposite of success; it's part of success.",
        "Be the change you wish to see in the world.",
        "Your only limit is you.",
        "Hustle in silence, let success make the noise.",
        "Doubt kills more dreams than failure ever will.",
        "Small steps every day lead to big results.",
        "Focus on the journey, not the destination.",
        "Impossible is just an opinion.",
        "The best way to predict the future is to create it.",
        "Believe you can and you're halfway there.",
        "Push yourself because no one else is going to do it for you.",
        "Do something today that your future self will thank you for.",
        "Don't wait for opportunity. Create it.",
        "Great things never come from comfort zones.",
        "Dream it. Wish it. Do it.",
        "Success doesn't come to you — you go to it.",
        "The harder you work for something, the greater you'll feel when you achieve it.",
        "Don’t stop until you’re proud.",
        "Wake up with determination. Go to bed with satisfaction.",
        "Your vibe attracts your tribe.",
        "Everything you’ve ever wanted is on the other side of fear.",
        "Opportunities don't happen. You create them.",
        "Sometimes later becomes never. Do it now.",
        "Don’t limit your challenges. Challenge your limits.",
        "Be fearless in the pursuit of what sets your soul on fire.",
        "Turn your wounds into wisdom.",
        "What we think, we become.",
        "Strive for progress, not perfection.",
        "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
        "It always seems impossible until it's done.",
        "Act as if what you do makes a difference. It does.",
        "Motivation gets you started. Habit keeps you going.",
        "Believe in your infinite potential.",
        "Do what you love, love what you do.",
        "Push yourself, because no one else is going to do it for you.",
        "The secret of getting ahead is getting started.",
        "Failure is another stepping stone to greatness.",
        "Success is not for the lazy.",
        "Be a voice, not an echo.",
        "When nothing goes right, go left.",
        "The comeback is always stronger than the setback.",
        "Work until your idols become rivals.",
        "A little progress each day adds up to big results.",
        "You are capable of amazing things.",
        "Don’t quit. Suffer now and live the rest of your life as a champion.",
        "Great things never come from comfort zones.",
        "Sometimes you win, sometimes you learn.",
        "If you’re going through hell, keep going.",
        "Success is the best revenge.",
        "Your limitation—it’s only your imagination.",
        "Don’t stop when you’re tired. Stop when you’re done.",
        "Success is not in what you have, but who you are.",
        "Do what is right, not what is easy.",
        "Make each day your masterpiece.",
        "Dreams don’t work unless you do.",
        "Don’t let yesterday take up too much of today.",
        "Believe in yourself and all that you are.",
        "Do something today that your future self will thank you for.",
        "Doubt kills more dreams than failure ever will.",
        "If it doesn’t challenge you, it won’t change you.",
        "Be so good they can’t ignore you.",
        "What you get by achieving your goals is not as important as what you become by achieving your goals.",
        "If you want it, work for it.",
        "Fall seven times and stand up eight.",
        "Success is walking from failure to failure with no loss of enthusiasm.",
        "Don’t count the days, make the days count.",
        "Push yourself, because no one else is going to do it for you.",
        "Your time is limited, don’t waste it living someone else’s life.",
        "Hard work beats talent when talent doesn’t work hard.",
        "The best revenge is massive success.",
        "Start where you are. Use what you have. Do what you can.",
        "Success is not how high you have climbed, but how you make a positive difference to the world.",
        "It’s going to be hard, but hard does not mean impossible.",
        "Be not afraid of going slowly, be afraid only of standing still.",
        "Don’t stop when you’re tired, stop when you’re done."
    ]

    static var randomQuote: String {
        quotes.randomElement() ?? "No quote available"
    }
}
